### ISSUE TITLE
Allow skipped or incomplete tests

### ISSUE THREAD

**Issue by stebogit** [mr-feek/LaravelGitHooks#30]
Hey @mr-feek , thanks for the nice tool 👍 

## Description
In my understanding the current code does not consider valid a `phpunit`result with warnings (e.g. `OK, but incomplete, skipped, or risky tests!`).
I do set some tests as skipped or incomplete during development as kind of reminders or TODOs, and I'd like to be able to push, for example, just as long as no test actually fails.

## Possible implementation
Not an expert on this, but I believe you could handle [the result](https://github.com/mr-feek/LaravelGitHooks/blob/master/src/Commands/PhpUnit.php#L57-L65) like:
```php
switch ($result) {
    case TestRunner::SUCCESS_EXIT:
        $this->info($this->commandOutputFormatter->success('Running PHPUnit'));
        return 0;
    case TestRunner::EXCEPTION_EXIT:
        $this->error($this->commandOutputFormatter->warn('Running PHPUnit'));
        return 0;
    case TestRunner::FAILURE_EXIT:
        $this->error($this->commandOutputFormatter->error('Running PHPUnit'));
        return 1;
}
```
Not sure if there are actually additional results to keep in account.

Maybe you could add an option to allow the user to define the behaviour in case of warnings. Here though I can't really help with the code... 😅 

## Your environment
MAC, PHP 7, Laravel 5.5, PHPUnit 6.4.3

**Note**: my `phpunit.xml` file contains:
```xml
     ...
     convertErrorsToExceptions="true"
     convertNoticesToExceptions="true"
     convertWarningsToExceptions="true"
```
and I also tried to add 
```xml
     failOnWarning="false"
     failOnRisky="false"
```
but the output of my tests (with a skipped or incomplete test) is always `2`, so the hook fails.

**Comment by mr-feek** [comment]
@stebogit great point! Skipped tests definitely shouldn't fail this hook. I'll address this when I have some spare time. Thanks for the detailed write up. For the time being, you can use your own phpunit artisan command.

**Comment by mr-feek** [comment]
I can't reproduce this anymore
