### ISSUE TITLE
Cannot install the package

### ISSUE THREAD

**Issue by BobbyBorisov** [mr-feek/LaravelGitHooks#34]
Guys, i have issue installing the package, i am installing screenshot. It obviously has some issue with versions of the dependencies but i have not idea how to fix it

<img width="1158" alt="screen shot 2018-09-05 at 12 14 43 am" src="https://user-images.githubusercontent.com/3647471/45058296-e9e2a200-b0a0-11e8-8d87-ffea1efb0341.png">

Thanks for the great package!

**Comment by mr-feek** [comment]
Hmmm solution here would be to have https://github.com/Weebly/phpstan-laravel/pull/19 merged and a new release made
