### ISSUE TITLE
Create Post Checkout Git Hook

### ISSUE THREAD

**Issue by mr-feek** [mr-feek/LaravelGitHooks#9]
use https://github.com/mr-feek/LaravelGitHooks/pull/8 as a guideline!

## Detailed description

I would like to allow developers to specify commands to be run during the `post-checkout` git hook.

## Possible implementation

- [ ] create bash file in `src/hooks` named `post-checkout.sh`, and can use the others as a template.
- [ ] edit `config/hooks.php` and add a new array key config for the `post-checkout` hook.
- [ ] create a new command in `src/Commands/CommitHooks` named `PostCheckout`, which extends `CommitHookCommand`. The `getConfigKey` function should be implemented to point to the configuration key created in the previous step.
- [ ] ensure that this new command [is made available](https://github.com/mr-feek/LaravelGitHooks/blob/master/src/LaravelGitHooksServiceProvider.php#L31)
- [ ] add the new `post-checkout.sh` file to the [list of files to be copied over](https://github.com/mr-feek/LaravelGitHooks/blob/master/src/Commands/InstallHooks.php#L35).

**Comment by rossdeane** [comment]
I'll grab this one 👍

**Comment by rossdeane** [comment]
Submitted #13 :)
